---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5c3e391a874290001d314f8c/webhook/forestry
sections:
- type: document
  path: config.yaml
  label: Config
  templates:
  - config
- type: document
  path: content/_index.md
  label: Home
  templates:
  - home
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
  templates:
  - page
- type: document
  path: content/elements.md
  label: Elements
  templates:
  - elements
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.47
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.47
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: '0.47'
